# Generated by Django 4.1.5 on 2024-02-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_customuser_username_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
