# Generated by Django 4.2 on 2024-02-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_rename_elements_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
