# Generated by Django 4.1.5 on 2024-02-06 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('html', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='template',
            name='html',
        ),
        migrations.AddField(
            model_name='template',
            name='elements',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='templates.templateelement'),
            preserve_default=False,
        ),
    ]
