# Generated by Django 4.1.5 on 2024-02-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_templateelement_remove_template_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='elements',
            field=models.TextField(),
        ),
    ]
