# Generated by Django 4.1.5 on 2024-02-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_customuser_otp'),
        ('templates', '0007_alter_template_elements'),
    ]

    operations = [
    ]
