# Generated by Django 4.1.5 on 2024-02-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0008_merge_20240212_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
