# Generated by Django 4.1.5 on 2024-02-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0011_remove_template_owner_alter_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
