# Generated by Django 4.2 on 2024-02-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0011_remove_template_owner_alter_template_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateElement',
        ),
    ]
