# Generated by Django 4.2 on 2024-02-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0013_template_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
