# Generated by Django 4.2 on 2024-02-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0012_alter_template_id'),
        ('templates', '0014_alter_customuser_id'),
    ]

    operations = [
    ]
